# lookup_wiki.py

OPERATORS = {
    "EDPC": {
        "operator": "EDP",
        "code3": "EDP",
        "operator:wikidata": "Q1341222",
        "brand": "edp Charge",
        "brand:wikidata": "Q1341222",
        "phone": "+351 800 222 222",
        "email": None,
    },
    "GLPP": {
        "operator": "Galp Power",
        "code3": "GLP",
        "operator:wikidata": "Q135275372",
        "brand": "Galp electric",
        "brand:wikidata": "Q135275372",
        "phone": "+351 800 249 249",
        "email": "veiculoeletrico@galp.com",
    },
    "HORZ": {
        "operator": "Powerdot",
        "code3": "HRZ",
        "operator:wikidata": "Q123574541",
        "brand": "Powerdot",
        "brand:wikidata": "Q123574541",
        "phone": "+351 800 180 292",
        "email": "ajuda@powerdot.pt",
    },
    "ATLA": {
        "operator": "Atlante",
        "code3": "ATL",
        "operator:wikidata": "Q126913632",
        "brand": "Atlante",
        "brand:wikidata": "Q126913632",
        "phone": "+351 800 296 929;+351 234 246 050",
        "email": "support.portugal@atlante.energy",
    },
    "TRUE": {
        "operator": "True Kare",
        "code3": "TRK",
        "operator:wikidata": None,
        "brand": "wowplug",
        "brand:wikidata": None,
        "phone": None,
        "email": "suporte@wowplug.com",
    },
    "KLCS": {
        "operator": "KLC Serviços",
        "code3": "KLS",
        "operator:wikidata": "Q127504745",
        "brand": "KLC",
        "brand:wikidata": "Q127504745",
        "phone": "+351 800 202 060",
        "email": "apoio.cliente@kmlowcost.com",
    },
    "MAKS": {
        "operator": "Maksu Services",
        "code3": "MAK",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": None,
        "email": "ev_portugal@maksu.com",
    },
    "IBRD": {
        "operator": "Iberdrola",
        "code3": "IBD",
        "operator:wikidata": "Q1437502",
        "brand": "Iberdrola",
        "brand:wikidata": "Q1437502",
        "phone": "+351 800 607 717",
        "email": "comercial@iberdrola.pt",
    },
    "HELX": {
        "operator": "Helexia II",
        "code3": "HLX",
        "operator:wikidata": None,
        "brand": "helexia",
        "brand:wikidata": None,
        "phone": "+351 210 181 157",
        "email": "geral.pt@helexia.eu",
    },
    "REPS": {
        "operator": "Repsol",
        "code3": "REP",
        "operator:wikidata": "Q174747",
        "brand": "Repsol",
        "brand:wikidata": "Q174747",
        "phone": "+351 800 226 624",
        "email": "crc.mobilidade.eletrica.pt@repsol.com",
    },
    "GLPG": {
        "operator": "Galp Geste",
        "code3": "GLG",
        "operator:wikidata": "Q1492739",
        "brand": "Galp electric",
        "brand:wikidata": "Q135275372",
        "phone": "+351 800 249 249",
        "email": "veiculoeletrico@galp.com",
    },
    "PRIO": {
        "operator": "Prio.E",
        "code3": "PRI",
        "operator:wikidata": None,
        "brand": "Prio",
        "brand:wikidata": "Q62530421",
        "phone": "+351 800 100 303",
        "email": "electric@prioenergy.com",
    },
    "FCTO": {
        "operator": "Charging Together",
        "code3": "FCT",
        "operator:wikidata": None,
        "brand": "Iberdrola bp pulse",
        "brand:wikidata": None,
        "phone": "+351 800 917 576",
        "email": None,
    },
    "MOTA": {
        "operator": "Mota Engil II",
        "code3": "MOT",
        "operator:wikidata": "Q1949595",
        "brand": "REMO",
        "brand:wikidata": None,
        "phone": "+351 800 020 940",
        "email": "renewing.charging@mota-engil.pt",
    },
    "REMO": {
        "operator": "REMO",
        "code3": "REM",
        "operator:wikidata": "Q1949595",
        "brand": "REMO",
        "brand:wikidata": None,
        "phone": "+351 800 020 940",
        "email": "renewing.charging@mota-engil.pt",
    },
    "MLTR": {
        "operator": "Mobiletric",
        "code3": "MLT",
        "operator:wikidata": None,
        "brand": "Mobiletric",
        "brand:wikidata": None,
        "phone": "+351 800 249 249",
        "email": "veiculoeletrico@galp.com",
    },
    "EMEL": {
        "operator": "EMEL",
        "code3": "EML",
        "operator:wikidata": "Q30256831",
        "brand": "leve",
        "brand:wikidata": "Q30256831",
        "phone": "+351 800 910 255",
        "email": "opc@emel.pt",
    },
    "ECOI": {
        "operator": "EcoInside",
        "code3": "ECI",
        "operator:wikidata": None,
        "brand": "ecoinside",
        "brand:wikidata": None,
        "phone": "+351 22 617 33 43",
        "email": "contact@ecoinside.pt",
    },
    "EVCE": {
        "operator": "EVCE",
        "code3": "EVC",
        "operator:wikidata": None,
        "brand": "MobiSmart",
        "brand:wikidata": None,
        "phone": "+351 800 301 303",
        "email": "info@mobismart.pt;info@evce.pt",
    },
    "SEGM": {
        "operator": "SEGMA",
        "code3": "SEG",
        "operator:wikidata": None,
        "brand": "SEGMA",
        "brand:wikidata": None,
        "phone": "+351 296 20 22 09",
        "email": "segma@segma.pt",
    },
    "FACT": {
        "operator": "Factor Energia",
        "code3": "FAC",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": "+351 800 100 013",
        "email": "info@factorenergia.pt",
    },
    "HEXA": {
        "operator": "Hexagonal Ocean",
        "code3": "HEX",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": None,
        "email": "geral@hexagonalocean.pt",
    },
    "DTEI": {
        "operator": "DTE",
        "code3": "DTE",
        "operator:wikidata": None,
        "brand": "e-flow",
        "brand:wikidata": None,
        "phone": "+351 912 872 459",
        "email": "geral@dte.pt",
    },
    "LOGI": {
        "operator": "Logical Gravity",
        "code3": "LOG",
        "operator:wikidata": None,
        "brand": "uCharge",
        "brand:wikidata": None,
        "phone": "+351 210 939 606;+351 224 801 080",
        "email": "geral@ucharge.pt",
    },
    "PLUG": {
        "operator": "Plug",
        "code3": "PLG",
        "operator:wikidata": None,
        "brand": "E-Plug",
        "brand:wikidata": None,
        "phone": None,
        "email": "geral@eplug.pt",
    },
    "MOON": {
        "operator": "Moon",
        "code3": "MOO",
        "operator:wikidata": None,
        "brand": "Moon",
        "brand:wikidata": None,
        "phone": None,
        "email": None,
    },
    "HIGH": {
        "operator": "High Green Power",
        "code3": "HGP",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": None,
        "email": None,
    },
    "EVPW": {
        "operator": "EV Power",
        "code3": "EVP",
        "operator:wikidata": None,
        "brand": "EVpower",
        "brand:wikidata": None,
        "phone": "+351 800 254 565",
        "email": "suporte@evpower.pt",
    },
    "EMAC": {
        "operator": "Emacom",
        "code3": "EMA",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": "+351 800 221 187",
        "email": "emacom-me@eem.pt",
    },
    "GENJ": {
        "operator": "Generation Journey",
        "code3": "GEN",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": None,
        "email": None,
    },
    "LOUL": {
        "operator": "Loulé Concelho Global",
        "code3": "LCG",
        "operator:wikidata": None,
        "brand": "loulé concelho Global",
        "brand:wikidata": None,
        "phone": "+351 289 401 080",
        "email": "geral@lcglobal.pt",
    },
    "VEIM": {
        "operator": "Veimonte",
        "code3": "VEI",
        "operator:wikidata": None,
        "brand": "powercharge",
        "brand:wikidata": None,
        "phone": "+351 266 896 443",
        "email": "info@powercharge.pt",
    },
    "CEPS": {
        "operator": "Cepsa",
        "code3": "CPS",
        "operator:wikidata": "Q608819",
        "brand": "Cepsa",
        "brand:wikidata": "Q608819",
        "phone": None,
        "email": None,
    },
    "BLUE": {
        "operator": "Bluecharge",
        "code3": "BLU",
        "operator:wikidata": "Q113289672",
        "brand": "Bluecharge",
        "brand:wikidata": "Q113289672",
        "phone": None,
        "email": "geral@bluecharge.pt",
    },
    "IONY": {
        "operator": "IONITY",
        "code3": "IOY",
        "operator:wikidata": "Q42717773",
        "brand": "IONITY",
        "brand:wikidata": "Q42717773",
        "phone": "+351 308 803 137",
        "email": None,
    },
    "GREE": {
        "operator": "GreenCharge",
        "code3": "GRN",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": "+351 800 210 432",
        "email": None,
    },
    "INTV": {
        "operator": "InstaVolt",
        "code3": "ITV",
        "operator:wikidata": "Q111173904",
        "brand": "Instavolt",
        "brand:wikidata": "Q111173904",
        "phone": "+351 800 783 433",
        "email": "info@instavolt.pt",
    },
    "ALFA": {
        "operator": "Alfa Energia",
        "code3": "ALF",
        "operator:wikidata": None,
        "brand": "ALFA Energia",
        "brand:wikidata": None,
        "phone": "+351 234 661 194",
        "email": "info@alfaenergia.pt",
    },
    "LUSI": {
        "operator": "Luzigás",
        "code3": "LUZ",
        "operator:wikidata": None,
        "brand": "Luzigás",
        "brand:wikidata": None,
        "phone": "+351 808 203 825",
        "email": "geral@luzigas.pt",
    },
    "EVIO": {
        "operator": "Evio",
        "code3": "EVI",
        "operator:wikidata": None,
        "brand": None,
        "brand:wikidata": None,
        "phone": "+351 308 803 746",
        "email": "evio@go-evio.com",
    },
    "PFTW": {
        "operator": "Plug Four The World",
        "code3": "PFU",
        "operator:wikidata": None,
        "brand": "Plug4Us",
        "brand:wikidata": None,
        "phone": "+351 800 100 995",
        "email": "support@plug4us.com",
    },
    "CAPW": {
        "operator": "CapWatt",
        "code3": "CAP",
        "operator:wikidata": None,
        "brand": "capWatt",
        "brand:wikidata": None,
        "phone": "+351 220 110 055",
        "email": "capwatt@capwatt.com",
    },
    "CABL": {
        "operator": "Cable Energia",
        "code3": "CAB",
        "operator:wikidata": None,
        "brand": "Shell Recharge",
        "brand:wikidata": "Q105883058",
        "phone": None,
        "email": None,
    },
    "ACCI": {
        "operator": "Acciona",
        "code3": "ACC",
        "operator:wikidata": "Q339142",
        "brand": "acciona",
        "brand:wikidata": "Q339142",
        "phone": None,
        "email": None,
    },
    "AUCH": {
        "operator": "Auchan",
        "code3": "AUC",
        "operator:wikidata": "Q119609729",
        "brand": "Auchan",
        "brand:wikidata": "Q758603",
        "phone": None,
        "email": None,
    },
    "MOBA": {
        "operator": "mobel",
        "code3": "MOA",
        "operator:wikidata": None,
        "brand": "mobel",
        "brand:wikidata": None,
        "phone": "+351 210 514 956",
        "email": "info@mobel.pt",
    },
    "VIAV": {
        "operator": "Via Verde",
        "code3": "VIA",
        "operator:wikidata": None,
        "brand": "Via Verde Electric",
        "brand:wikidata": None,
        "phone": None,
        "email": None,
    },
    "FRTR": {
        "operator": "Frontrow",
        "code3": "FRR",
        "operator:wikidata": None,
        "brand": "Luz Verde",
        "brand:wikidata": None,
        "phone": "+351 255 810 219;+351 910 370 878",
        "email": "geral@luz-verde.pt",
    },
}

